---
swagger: "2.0"
info:
  description: "Documentation de l'api privée megacasting"
  version: "0.1"
  title: "MegaCasting private API documentation"
host: "megacastingprivateapi.azurewebsites.net"
tags:
- name: "adresse"
  description: "adresse CRUD"
- name: "Utilisateur"
  description: "Ajout et authentification"
paths:
  /adresse:
    get:
      tags:
      - "adresse"
      summary: "Permet de récupérer toutes les adresses"
      operationId: "adresseGET"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Retourne une liste d'adresses"
          schema:
            $ref: "#/definitions/Adresses"
      x-swagger-router-controller: "Adresse"
    post:
      tags:
      - "adresse"
      summary: "Permet d'ajouter une adresse"
      operationId: "adressePOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/AdresseWithoutId"
        x-examples:
          application/json: "{\n    \"ADR_NUM_VOIE\": \"25\",\n    \"ADR_LIBELLE_RUE\"\
            : \"rue de la liberté\",\n    \"ADR_VILLE\": \"Brest\"\n}"
      responses:
        201:
          description: "Retourne l'adresse créée avec son id"
          schema:
            $ref: "#/definitions/Adresse"
      x-swagger-router-controller: "Adresse"
  /adresse/{adresseId}:
    get:
      tags:
      - "adresse"
      operationId: "adresseAdresseIdGET"
      produces:
      - "application/json"
      parameters:
      - name: "adresseId"
        in: "path"
        description: "ID de l'adresse recherchée"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Definition generated from Swagger Inspector"
          schema:
            $ref: "#/definitions/Adresse"
      x-swagger-router-controller: "Adresse"
    put:
      tags:
      - "adresse"
      operationId: "adresseAdresseIdPUT"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "adresseId"
        in: "path"
        description: "ID de l'adresse recherchée"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/AdresseWithoutId"
        x-examples:
          application/json: "{\n    \"ADR_NUM_VOIE\": \"25\",\n    \"ADR_LIBELLE_RUE\"\
            : \"rue de la liberté\",\n    \"ADR_VILLE\": \"Laval\"\n}"
      responses:
        200:
          description: "Definition generated from Swagger Inspector"
          schema:
            $ref: "#/definitions/Adresse"
      x-swagger-router-controller: "Adresse"
  /auth/signup:
    post:
      tags:
      - "utilisateur"
      operationId: "authSignupPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/User"
        x-examples:
          application/json: "{\n    \"UTI_NOM\": \"Jean\",\n    \"UTI_PRENOM\": \"\
            Bob\",\n    \"UTI_LOGIN\": \"JBob\",\n    \"UTI_MDP\": \"azerty123\",\n\
            \    \"UTI_ADMINISTRATEUR\": true\n}"
      responses:
        200:
          description: "Definition generated from Swagger Inspector"
          schema:
            $ref: "#/definitions/SignupReturn"
      x-swagger-router-controller: "Utilisateur"
  /auth/login:
    post:
      tags:
      - "utilisateur"
      operationId: "authLoginPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/User"
        x-examples:
          application/json: "{\n    \"UTI_LOGIN\": \"JBob\",\n    \"UTI_MDP\": \"\
            azerty123\"\n}"
      responses:
        201:
          description: "Definition generated from Swagger Inspector"
          schema:
            $ref: "#/definitions/LoginReturn"
      x-swagger-router-controller: "Utilisateur"
definitions:
  User:
    properties:
      UTI_NOM:
        type: "string"
      UTI_PRENOM:
        type: "string"
      UTI_LOGIN:
        type: "string"
      UTI_MDP:
        type: "string"
      UTI_ADMINISTRATEUR:
        type: "boolean"
    example:
      UTI_ADMINISTRATEUR: true
      UTI_LOGIN: "UTI_LOGIN"
      UTI_PRENOM: "UTI_PRENOM"
      UTI_MDP: "UTI_MDP"
      UTI_NOM: "UTI_NOM"
  AdresseWithoutId:
    properties:
      ADR_NUM_VOIE:
        type: "string"
      ADR_LIBELLE_RUE:
        type: "string"
      ADR_VILLE:
        type: "string"
    example:
      ADR_NUM_VOIE: "ADR_NUM_VOIE"
      ADR_LIBELLE_RUE: "ADR_LIBELLE_RUE"
      ADR_VILLE: "ADR_VILLE"
  Adresse:
    properties:
      ADR_ID:
        type: "integer"
        format: "int32"
      ADR_NUM_VOIE:
        type: "string"
      ADR_LIBELLE_RUE:
        type: "string"
      ADR_VILLE:
        type: "string"
    example:
      ADR_ID: 0
      ADR_NUM_VOIE: "ADR_NUM_VOIE"
      ADR_LIBELLE_RUE: "ADR_LIBELLE_RUE"
      ADR_VILLE: "ADR_VILLE"
  Adresses:
    properties:
      adresse:
        type: "array"
        items:
          $ref: "#/definitions/Adresse"
    example:
      adresse:
      - ADR_ID: 0
        ADR_NUM_VOIE: "ADR_NUM_VOIE"
        ADR_LIBELLE_RUE: "ADR_LIBELLE_RUE"
        ADR_VILLE: "ADR_VILLE"
      - ADR_ID: 0
        ADR_NUM_VOIE: "ADR_NUM_VOIE"
        ADR_LIBELLE_RUE: "ADR_LIBELLE_RUE"
        ADR_VILLE: "ADR_VILLE"
  SignupReturn:
    properties:
      message:
        type: "string"
      id:
        type: "integer"
        format: "int32"
      nom:
        type: "string"
      prenom:
        type: "string"
      login:
        type: "string"
    example:
      id: 0
      message: "message"
      login: "login"
      nom: "nom"
      prenom: "prenom"
  LoginReturn:
    properties:
      token:
        type: "string"
      userId:
        type: "string"
    example:
      userId: "userId"
      token: "token"
